# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

# osx_image: xcode7.3
osx_image: xcode12.5.1
language: objective-c


env:
  matrix:
    - TEST_SDK=iphonesimulator14.7 OS=14.7 NAME='iPhone 12 Pro'
    - TEST_SDK=iphonesimulator14.7 OS=14.7 NAME='iPhone 12'

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TFLiteSwift-Vision.xcworkspace -scheme TFLiteSwift-Vision-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint
 
