use_frameworks!

platform :ios, '10.0'

target 'TFLiteSwift-Vision_Example' do
  pod 'TFLiteSwift-Vision', :path => '../../'

#  target 'TFLiteSwift-Vision_Tests' do
#    inherit! :search_paths
#
#    
#  end
  
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
